### ISSUE TITLE
Provide checks for unused ids

### ISSUE THREAD

**Issue by tpgmartin** [benedfit/stylinpug#40]
Hey @benedfit I really like this library, would you be willing to allow me to contribute a pr to highlight unused ids as per class selectors? Cheers

**Comment by benedfit** [comment]
Hi @tpgmartin

Sure I'd be happy for you to contribute, sorry I haven't added a Contribution Guide yet, but if you're PR could try and provide tests to keep the coverage up at 100% that would be great, and if you run `npm test` before pushing to make sure the js style is consistent those are my only requirements really

One thing I'll add is that the option to check ids needs to optional, and I'd like the default to be if an id is found in the CSS then an error should be returned. I only ask this as my personal preference is never to style ids

So perhaps the new config option could be `allowIdAttributes: false | true`?

Please let me know if I've made this more complicated than you'd like, and I'd be happy to add this feature instead :)

**Comment by benedfit** [comment]
I've added the first draft of a Contribution guide, please let me know if it's missing anything

**Comment by tpgmartin** [comment]
No problem I'll get on when I can, thanks for your reply.
